<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    // $templateType =  \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
	
	$meigee_helper = $this->helper('\Meigee\Underlinen\Helper\UnderlinenGeneral');
	$lightbox_status = $meigee_helper->getCustomThemeOptionCnf('underlinen_lightbox', 'lightbox_status');
	$lightbox_widget_status = $meigee_helper->getCustomThemeOptionCnf('underlinen_lightbox', 'lightbox_home');
	$name_align = $meigee_helper->getCustomThemeOptionCnf('underlinen_product_listing', 'product_name_aligment');
	$stock_status = $meigee_helper->getCustomThemeOptionCnf('underlinen_product_listing', 'stock_status');
	
?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode .' '. $type; ?>">
                <ol class="product-items row">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item col-sm-3">' : '</li><li class="item col-sm-3">' ?>
                        <div class="product-item-info">
							<div class="image-wrapper">
								<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
									<?php echo $block->getImage($_item, $image)->toHtml(); ?>
								</a>
								<?php if($lightbox_status && $lightbox_widget_status){ ?>
									<a href="<?php echo $block->getImage($_item, $image)->getImageUrl();  ?>" data-toggle="lightbox" class="lightbox-button" data-footer="<?php echo $block->escapeHtml($_item->getName()); ?>" title="<?php echo __('Lightbox'); ?>">
										<i class="ion-ios-search-strong"></i>
									</a>
								<?php } ?>
								<?php if ($showWishlist || $showCompare): ?>
									<div class="add-to-links" data-role="add-to-links">
										<div class="links-inner clearfix">
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
												<a href="#"
												   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
												   class="action towishlist" data-action="add-to-wishlist"
												   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
													<i class="ion-heart"></i>
												</a>
											<?php endif; ?>
											<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
												<a href="#" class="action tocompare"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
												   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
													<i class="ion-arrow-swap"></i>
												</a>
											<?php endif; ?>
											
										</div>
									</div>
								<?php endif; ?>
							</div>
                            <div class="product-item-details">
                                <h4 class="product-item-name <?php echo $name_align; ?>">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </h4>
                                <?php if ($templateType): ?>
									<?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                <?php endif; ?>
								<?php if($stock_status != 4 && $stock_status != 2) { 
									if ($_item->getIsSalable()): ?>
										<div class="stock available"><?php /* @escapeNotVerified */ echo __('Availability') ?><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><?php /* @escapeNotVerified */ echo __('Availability') ?><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
									<?php endif; 
								} ?>
								<div class="price-links-block">
									<?php echo $block->getProductPriceHtml($_item, $type); ?>
								</div>
								<?php if ($showCart): ?>
									<div class="button-wrapper">
										<?php if ($_item->isSaleable()): ?>
											<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
												<button class="btn btn-default btn-cart action tocart"
														data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
														type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
													<i class="ion-android-cart"></i>
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											<?php else: ?>
												<?php
													$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
													$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
												?>
												<button class="btn btn-default btn-cart"
														data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
														type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
													<i class="ion-android-cart"></i>
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											<?php endif; ?>
										<?php else: ?>
											<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo __('Read more') ?>" class="btn btn-default btn-cart"><i class="ion-ios-eye"></i><?php echo __('Read more') ?></a>
										<?php endif; ?>
									</div>
								<?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
